#!/bin/bash
# commandline ewxample;
# clear && time ./LONGANIM -P -A -M &&  xsel -o > run.log

#!@ wipe all stale state flags
rm /tmp/abort.flag

NAME="spagvik"
CFG="/home/jw/src/sdc/settings/COMFY/${NAME}"
VER=`./getcval.py -c ${CFG} -k version`

prep () {
  rm /tmp/fgroups.json;
  rm /tmp/fgroups_ct.json;
  ./long_anim_v4.py --stage prep -D ${CFG}  --version ${VER} --flatprompt;
}

anim () {
  ./long_anim_v4.py --stage anim -D ${CFG}  --version ${VER} --flatprompt;
}

merge () {
  ./long_anim_v4.py --stage merge -D ${CFG} --version ${VER} #--experimental ; # fswap;
}

# make sure V is first
while getopts 'PAM' option ; do
    case "${option}" in
    P) prep  ;;
    A) anim  ;;
    M) merge ;;
    *) echo "NO OPTS!?" ;;
    esac
done
shift $(( OPTIND - 1 ))

