#!/bin/bash

#export TCLLIBPATH="/usr/lib/graphviz /usr/lib/expect5.45.4/ $TCLLIBPATH"

while getopts ":i:o:" d; do
    case "${d}" in
        i)
            istr="--input-directory ${OPTARG}"
            ;;
        o)
            ostr="--output-directory ${OPTARG}"
            ;;
        *)
            usage
            ;;
    esac
done

export HSA_OVERRIDE_GFX_VERSION=10.3.0 python main.py $args
export NUMEXPR_MAX_THREADS=128

GPUMEMCLEAR
sleep 2

#cd /home/jw/src/ComfyUI-Installer/ComfyUI
#source comfy-venv/bin/activate

# PREVIOUS
cd /home/jw/src/ComfyUI

RUNNING=`cat /etc/issue|awk '{print $1}'`

source /home/jw/miniforge3/etc/profile.d/conda.sh
conda activate comfy



SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PYTHON_SCRIPTS_DIR="$PYTHON_DIR/Scripts;/home/jw/store/src/ComfyUI/custom_nodes/comfyui-reactor-node/"
export PATH="$PYTHON_SCRIPTS_DIR:$PYTHON_LIB_DIR:$PYTHON_DIR:$PATH"

echo "------------------------------------------------------------------------------"
echo "python ./main.py --preview-method auto --force-fp16  --bf16-vae ${istr} ${ostr}"
echo "------------------------------------------------------------------------------"

#python ./main.py --preview-method auto --disable-smart-memory --force-fp16  --bf16-vae ${istr} ${ostr} 2>&1 > /tmp/START.log
python ./main.py --preview-method auto --force-fp16  --bf16-vae --port 8090 ${istr} ${ostr} #2>&1 > /tmp/START.log

