#!/bin/bash
clear
cd ~/src/longanim

find -type f -name "*.json"|grep -v API|grep -v archive|grep -v clean|grep "json"|awk '{print " ./updateFilename.py -f "$0}' > RUN
#find -type f -name "*.json"|grep -v API|grep -v archive|grep -v clean|grep "json"|head -1|awk '{print " ./updateFilename.py -f "$0}' > RUN
sh ./RUN |tee update.log




